# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jul  3 14:12:56 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 523)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 621, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_name = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_name.sizePolicy().hasHeightForWidth())
        self.txt_name.setSizePolicy(sizePolicy)
        self.txt_name.setMaxLength(200)
        self.txt_name.setObjectName("txt_name")
        self.gridLayout.addWidget(self.txt_name, 2, 0, 1, 1)
        self.lbl_txt_name = QtGui.QLabel(self.gridLayoutWidget)
        self.lbl_txt_name.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lbl_txt_name.setObjectName("lbl_txt_name")
        self.gridLayout.addWidget(self.lbl_txt_name, 0, 0, 1, 1)
        self.btn_search = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.gridLayout.addWidget(self.btn_search, 2, 1, 1, 1)
        self.btn_clear = QtGui.QPushButton(self.gridLayoutWidget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 2, 2, 1, 1)
        self.tab_character = QtGui.QTabWidget(self.centralwidget)
        self.tab_character.setGeometry(QtCore.QRect(10, 80, 621, 421))
        self.tab_character.setTabPosition(QtGui.QTabWidget.North)
        self.tab_character.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_character.setObjectName("tab_character")
        self.tab_character_info = QtGui.QWidget()
        self.tab_character_info.setObjectName("tab_character_info")
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_character_info)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.lbl_character_id = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_character_id.setObjectName("lbl_character_id")
        self.horizontalLayout_26.addWidget(self.lbl_character_id)
        self.lbl_character_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_character_value.setText("")
        self.lbl_character_value.setObjectName("lbl_character_value")
        self.horizontalLayout_26.addWidget(self.lbl_character_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.lbl_name = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_27.addWidget(self.lbl_name)
        self.lbl_name_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_name_value.setText("")
        self.lbl_name_value.setObjectName("lbl_name_value")
        self.horizontalLayout_27.addWidget(self.lbl_name_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_server = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_server.setObjectName("lbl_server")
        self.horizontalLayout_6.addWidget(self.lbl_server)
        self.lbl_server_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_server_value.setText("")
        self.lbl_server_value.setObjectName("lbl_server_value")
        self.horizontalLayout_6.addWidget(self.lbl_server_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_faction = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_faction.setObjectName("lbl_faction")
        self.horizontalLayout_5.addWidget(self.lbl_faction)
        self.lbl_faction_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_faction_value.setText("")
        self.lbl_faction_value.setObjectName("lbl_faction_value")
        self.horizontalLayout_5.addWidget(self.lbl_faction_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lbl_rank = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_rank.sizePolicy().hasHeightForWidth())
        self.lbl_rank.setSizePolicy(sizePolicy)
        self.lbl_rank.setObjectName("lbl_rank")
        self.horizontalLayout_28.addWidget(self.lbl_rank)
        self.lbl_rank_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_rank_value.setText("")
        self.lbl_rank_value.setObjectName("lbl_rank_value")
        self.horizontalLayout_28.addWidget(self.lbl_rank_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.lbl_timeplayed = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_timeplayed.setObjectName("lbl_timeplayed")
        self.horizontalLayout_29.addWidget(self.lbl_timeplayed)
        self.lbl_timeplayed_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_timeplayed_value.setText("")
        self.lbl_timeplayed_value.setObjectName("lbl_timeplayed_value")
        self.horizontalLayout_29.addWidget(self.lbl_timeplayed_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.lbl_score = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_score.setObjectName("lbl_score")
        self.horizontalLayout_30.addWidget(self.lbl_score)
        self.lbl_score_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_score_value.setText("")
        self.lbl_score_value.setObjectName("lbl_score_value")
        self.horizontalLayout_30.addWidget(self.lbl_score_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lbl_spm = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_spm.setObjectName("lbl_spm")
        self.horizontalLayout_21.addWidget(self.lbl_spm)
        self.lbl_spm_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_spm_value.setText("")
        self.lbl_spm_value.setObjectName("lbl_spm_value")
        self.horizontalLayout_21.addWidget(self.lbl_spm_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lbl_sph = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_sph.setObjectName("lbl_sph")
        self.horizontalLayout_22.addWidget(self.lbl_sph)
        self.lbl_sph_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_sph_value.setText("")
        self.lbl_sph_value.setObjectName("lbl_sph_value")
        self.horizontalLayout_22.addWidget(self.lbl_sph_value)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_total_certs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_total_certs.setObjectName("lbl_total_certs")
        self.horizontalLayout_7.addWidget(self.lbl_total_certs)
        self.lbl_total_certs_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_total_certs_value.setText("")
        self.lbl_total_certs_value.setObjectName("lbl_total_certs_value")
        self.horizontalLayout_7.addWidget(self.lbl_total_certs_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_certs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_certs.setObjectName("lbl_certs")
        self.horizontalLayout_4.addWidget(self.lbl_certs)
        self.lbl_certs_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_certs_value.setText("")
        self.lbl_certs_value.setObjectName("lbl_certs_value")
        self.horizontalLayout_4.addWidget(self.lbl_certs_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lbl_gifted_certs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_gifted_certs.setObjectName("lbl_gifted_certs")
        self.horizontalLayout_10.addWidget(self.lbl_gifted_certs)
        self.lbl_gifted_certs_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_gifted_certs_value.setText("")
        self.lbl_gifted_certs_value.setObjectName("lbl_gifted_certs_value")
        self.horizontalLayout_10.addWidget(self.lbl_gifted_certs_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_spent_certs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_spent_certs.setObjectName("lbl_spent_certs")
        self.horizontalLayout_3.addWidget(self.lbl_spent_certs)
        self.lbl_spent_certs_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_spent_certs_value.setText("")
        self.lbl_spent_certs_value.setObjectName("lbl_spent_certs_value")
        self.horizontalLayout_3.addWidget(self.lbl_spent_certs_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.lbl_percentage_to_next = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_percentage_to_next.setObjectName("lbl_percentage_to_next")
        self.horizontalLayout_25.addWidget(self.lbl_percentage_to_next)
        self.lbl_percentage_to_next_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_percentage_to_next_value.setText("")
        self.lbl_percentage_to_next_value.setObjectName("lbl_percentage_to_next_value")
        self.horizontalLayout_25.addWidget(self.lbl_percentage_to_next_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lbl_available_certs = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_available_certs.setObjectName("lbl_available_certs")
        self.horizontalLayout_8.addWidget(self.lbl_available_certs)
        self.lbl_available_certs_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_available_certs_value.setText("")
        self.lbl_available_certs_value.setObjectName("lbl_available_certs_value")
        self.horizontalLayout_8.addWidget(self.lbl_available_certs_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lbl_cpm = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cpm.sizePolicy().hasHeightForWidth())
        self.lbl_cpm.setSizePolicy(sizePolicy)
        self.lbl_cpm.setObjectName("lbl_cpm")
        self.horizontalLayout_23.addWidget(self.lbl_cpm)
        self.lbl_cpm_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_cpm_value.setText("")
        self.lbl_cpm_value.setObjectName("lbl_cpm_value")
        self.horizontalLayout_23.addWidget(self.lbl_cpm_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.lbl_cph = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_cph.setObjectName("lbl_cph")
        self.horizontalLayout_24.addWidget(self.lbl_cph)
        self.lbl_cph_value = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_cph_value.setText("")
        self.lbl_cph_value.setObjectName("lbl_cph_value")
        self.horizontalLayout_24.addWidget(self.lbl_cph_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tab_character.addTab(self.tab_character_info, "")
        self.tab_KDR = QtGui.QWidget()
        self.tab_KDR.setObjectName("tab_KDR")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_KDR)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 611, 291))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_51 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_31.addWidget(self.label_51)
        self.label_52 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_31.addWidget(self.label_52)
        self.verticalLayout_6.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_53 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_32.addWidget(self.label_53)
        self.label_54 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_32.addWidget(self.label_54)
        self.verticalLayout_6.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_55 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_33.addWidget(self.label_55)
        self.label_56 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_33.addWidget(self.label_56)
        self.verticalLayout_6.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_57 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_34.addWidget(self.label_57)
        self.label_58 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_34.addWidget(self.label_58)
        self.verticalLayout_6.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_59 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_35.addWidget(self.label_59)
        self.label_60 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_35.addWidget(self.label_60)
        self.verticalLayout_6.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_61 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_36.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_36.addWidget(self.label_62)
        self.verticalLayout_7.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_63 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_37.addWidget(self.label_63)
        self.label_64 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_37.addWidget(self.label_64)
        self.verticalLayout_7.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_65 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_38.addWidget(self.label_65)
        self.label_66 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_38.addWidget(self.label_66)
        self.verticalLayout_7.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_67 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_39.addWidget(self.label_67)
        self.label_68 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_39.addWidget(self.label_68)
        self.verticalLayout_7.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_69 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_40.addWidget(self.label_69)
        self.label_70 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_40.addWidget(self.label_70)
        self.verticalLayout_7.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.tab_character.addTab(self.tab_KDR, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_character.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.txt_name.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Thoross", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_txt_name.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_search.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_character_id.setText(QtGui.QApplication.translate("MainWindow", "Character ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_name.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_server.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Server:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_faction.setText(QtGui.QApplication.translate("MainWindow", "Faction:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_rank.setText(QtGui.QApplication.translate("MainWindow", "Rank:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_timeplayed.setText(QtGui.QApplication.translate("MainWindow", "Time Played:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_score.setText(QtGui.QApplication.translate("MainWindow", "Score:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_spm.setText(QtGui.QApplication.translate("MainWindow", "Score Per Minute:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sph.setText(QtGui.QApplication.translate("MainWindow", "Score Per Hour:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_total_certs.setText(QtGui.QApplication.translate("MainWindow", "Total Certs Accumulated:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_certs.setText(QtGui.QApplication.translate("MainWindow", "Certs Earned:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_gifted_certs.setText(QtGui.QApplication.translate("MainWindow", "Certs Gifted:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_spent_certs.setText(QtGui.QApplication.translate("MainWindow", "Certs Spent:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_percentage_to_next.setText(QtGui.QApplication.translate("MainWindow", "Percentage to Next Cert:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_available_certs.setText(QtGui.QApplication.translate("MainWindow", "Available Certs:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_cpm.setText(QtGui.QApplication.translate("MainWindow", "Certs Per Minute:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_cph.setText(QtGui.QApplication.translate("MainWindow", "Certs Per Hour:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_character.setTabText(self.tab_character.indexOf(self.tab_character_info), QtGui.QApplication.translate("MainWindow", "Character Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_character.setTabText(self.tab_character.indexOf(self.tab_KDR), QtGui.QApplication.translate("MainWindow", "Kills and Deaths", None, QtGui.QApplication.UnicodeUTF8))

